// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace CoreGateway.Storage.Service.DbModel
{
	[Table("file_data")]
	public class FileDatum
	{
		[Column("id"  , IsPrimaryKey = true)] public Guid    Id   { get; set; } // uuid
		[Column("name"                     )] public string? Name { get; set; } // text
		[Column("data"                     )] public byte[]? Data { get; set; } // bytea
	}
}
