// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace CoreGateway.Storage.Service.DbModel
{
	public partial class StorageDb : DataConnection
	{
		public StorageDb()
		{
			InitDataContext();
		}

		public StorageDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public StorageDb(DataOptions<StorageDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<FileDatum> FileData => this.GetTable<FileDatum>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static FileDatum? Find(this ITable<FileDatum> table, Guid id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<FileDatum?> FindAsync(this ITable<FileDatum> table, Guid id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
